---
name: Cargo Build & Test

on:  # yamllint disable-line rule:truthy
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Install dependencies
        run: >
          sudo apt-get update
          && sudo apt-get install --no-install-recommends --yes
          bzip2 lz4 lzop xz-utils zstd
      - uses: actions/checkout@v4
      - run: >
          rustup update ${{ matrix.toolchain }}
          && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
